/**
 * AutoQA Environment Helper
 *
 * This file is generated by `autoqa init` and provides environment variable
 * loading utilities for generated Playwright tests.
 */
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'

function stripQuotes(value: string): string {
  const s = value.trim()
  if (s.length >= 2 && ((s.startsWith('"') && s.endsWith('"')) || (s.startsWith("'") && s.endsWith("'")))) {
    return s.slice(1, -1)
  }
  return s
}

function parseDotEnv(content: string): Record<string, string> {
  const out: Record<string, string> = {}
  const lines = (content ?? '').split(/\r?\n/g)
  for (const rawLine of lines) {
    const line = rawLine.trim()
    if (!line) continue
    if (line.startsWith('#')) continue
    const withoutExport = line.startsWith('export ') ? line.slice('export '.length).trim() : line
    const eqIndex = withoutExport.indexOf('=')
    if (eqIndex <= 0) continue
    const key = withoutExport.slice(0, eqIndex).trim()
    if (!key) continue
    const rawValue = withoutExport.slice(eqIndex + 1)
    out[key] = stripQuotes(rawValue)
  }
  return out
}

function loadEnvFile(fileName: string, initialEnvKeys: Set<string>): void {
  const absPath = join(process.cwd(), fileName)
  if (!existsSync(absPath)) return
  const parsed = parseDotEnv(readFileSync(absPath, 'utf8'))
  for (const [k, v] of Object.entries(parsed)) {
    if (initialEnvKeys.has(k)) continue
    process.env[k] = v
  }
}

/**
 * Load .env and .env.<env> files from the current working directory.
 *
 * - Loads .env first (if exists)
 * - Then loads .env.<AUTOQA_ENV> if AUTOQA_ENV is set (e.g., .env.test)
 * - Does not override environment variables that were already set
 *
 * Example:
 *   // .env
 *   AUTOQA_BASE_URL=https://example.com
 *   AUTOQA_ENV=test
 *
 *   // .env.test
 *   TEST_USER=test@example.com
 *
 *   loadEnvFiles()
 *   // process.env.AUTOQA_BASE_URL = 'https://example.com'
 *   // process.env.AUTOQA_ENV = 'test'
 *   // process.env.TEST_USER = 'test@example.com'
 */
export function loadEnvFiles(): void {
  const initialEnvKeys = new Set(Object.keys(process.env))
  loadEnvFile('.env', initialEnvKeys)
  const envName = (process.env.AUTOQA_ENV ?? '').trim()
  if (envName) {
    loadEnvFile('.env.' + envName, initialEnvKeys)
  }
}

/**
 * Get an environment variable value or throw an error if missing.
 *
 * @param key - The environment variable name
 * @returns The environment variable value
 * @throws Error if the environment variable is not set
 *
 * Example:
 *   const baseUrl = getEnvVar('AUTOQA_BASE_URL')
 */
export function getEnvVar(key: string): string {
  const value = process.env[key]
  if (!value) {
    throw new Error(`Missing required environment variable: ${key}`)
  }
  return value
}
